### ISSUE TITLE
Outdated intro page on the website

### ISSUE THREAD

**Issue by TomasTomecek** [qiot-project/qiot-project.github.io#13]
Please update your initial intro on the webpage:

    A few months ago, back in November 2020

It's November 2021 when I'm reading this :)

**Comment by andreabattaglia** [comment]
Hi Tomas,

I finally had time to fix the issue.
Please feel free to check and review both the "welcome" and the "community" sections.

Andrea

**Comment by TomasTomecek** [comment]
Works for me, thanks Andrea!
